GRPC Transactions System Server
-------------------------------

Задачка от technology development center 

И так, что тут есть?

* GRPC микросервис обработки транзакций (перевода денег)
* Deposit для пополнения, withdrawn для перевода другому пользователю 
* Реализовано через шедулер и транзакции, по этому сервис устойчив к сохранности данных при "падении" (можно было бы и через брокер, но так в разы проще и быстрее)
* Interceptors (на логгирование и трейс)
* env, ldflags (в этот раз без докера, увы)
* Куча логов и трейсов
* PostgreSQL хранилище, migrations, transactions, keys, autoUpdateDate, softDelete, 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

p.s. написал я все это добро и отладил за 3 часа сидя в башне федерации пока не сел макбук, позднее уже дома сделал заключительный коммит подсосавшись к зарядке, так что не считается. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
В сумме на задачу потратил 3-3.5 часа от А до Я.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
